[package]
name = "boys"
version = "0.1.0"
edition = "2021"

[lib]
name = "boys"
path = "src/lib.rs"

[[bin]]
name = "boys"
path = "src/main.rs"

[dependencies]
libm = "0.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "boys_bench"
harness = false
